FROM ubuntu
RUN apt-get update -y
RUN apt-get install wget -y
RUN wget https://github.com/OrenGitHub/dhscanner/releases/download/v0.0.1/codegen.elf.aarch64
RUN chmod +x codegen.elf.aarch64
CMD ["./codegen.elf.aarch64"]